# Generated by Django 4.2.2 on 2023-06-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bairro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Bebida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("imagem", models.ImageField(null=True, upload_to="")),
                ("preco", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tamanho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        choices=[
                            ("gigante", "gigante"),
                            ("grande", "grande"),
                            ("media", "media"),
                        ],
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoBebida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Refrigerante", "Refrigerante"),
                            ("suco", "suco"),
                            ("água", "água"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=5)),
                ("imagem", models.ImageField(null=True, upload_to="")),
                (
                    "outro_sabor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pizzaria_Mamma_Mia.pizza",
                    ),
                ),
                (
                    "tamanho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pizzaria_Mamma_Mia.tamanho",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("data", models.DateTimeField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "fk_bebida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pizzaria_Mamma_Mia.bebida",
                    ),
                ),
                (
                    "fk_pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pizzaria_Mamma_Mia.pizza",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=50)),
                ("numero", models.IntegerField()),
                ("complemento", models.CharField(max_length=20, null=True)),
                ("CEP", models.CharField(max_length=8)),
                (
                    "fk_bairro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pizzaria_Mamma_Mia.bairro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="composicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk_ingredientes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pizzaria_Mamma_Mia.ingrediente",
                    ),
                ),
                (
                    "fk_pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pizzaria_Mamma_Mia.pizza",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("telefone", models.CharField(max_length=13, unique=True)),
                (
                    "fk_endereco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pizzaria_Mamma_Mia.endereco",
                    ),
                ),
                (
                    "fk_pedidos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pizzaria_Mamma_Mia.pedido",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bebida",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Pizzaria_Mamma_Mia.tipobebida",
            ),
        ),
    ]
