# Generated by Django 4.2.1 on 2023-06-07 19:49

from django.db import migrations, models
import django.db.models.deletion

# cria os valores das tabelas com choices
def add_bebidas(apps, schema_editor):
    tipo_bebida = apps.get_model('Pizzaria_Mamma_Mia', 'TipoBebida')
    for bebida, _read in tipo_bebida.name.field.choices:
        tipo_bebida.objects.create(name=bebida)

def add_tamanhos(apps, schema_editor):
    tamanho = apps.get_model('Pizzaria_Mamma_Mia', 'Tamanho')
    for tam, _read in tamanho.tamanho.field.choices:
        tamanho.objects.create(tamanho=tam)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ele deve ser executado após o 0001_initial
        ('Pizzaria_Mamma_Mia', '0001_initial'),
    ]

    operations = [

        migrations.RunPython(add_bebidas),
        migrations.RunPython(add_tamanhos),

    ]

