# Generated by Django 4.2.2 on 2023-06-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Pizzaria_Mamma_Mia", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combo",
            name="fk_pizza",
        ),
        migrations.AddField(
            model_name="combo",
            name="fk_pizza_1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pizza_1",
                to="Pizzaria_Mamma_Mia.pizza",
            ),
        ),
        migrations.AddField(
            model_name="combo",
            name="fk_pizza_2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pizza_2",
                to="Pizzaria_Mamma_Mia.pizza",
            ),
        ),
        migrations.AddField(
            model_name="combo",
            name="imagem",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
