# Generated by Django 4.2.2 on 2023-06-27 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Pizzaria_Mamma_Mia", "0003_remove_combo_fk_pizza_combo_fk_pizza_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="fk_bebida",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Pizzaria_Mamma_Mia.bebida",
            ),
        ),
    ]
